### ISSUE TITLE
مشکل ارتفاع و آیکون

### ISSUE THREAD

**Issue by Azare77** [shirvanie/flutter_story#1]
درود یه چند تا نکته دیدم که به نظرم بهتره توجه کنی بهشون
اولی ارتفاع ردیف هست که یه قداری زیاده به خاطر سایز بالا اون دایره که وقتی ارتفاع ست میکنم روی StoryUser تاثیر نداره و وقتی StoryUser رو تغییر میدم دیگه اون شکل دایره بودن رو از دست میده
دومی هم اینکه توی اندروید های قدیمی تر حدود 10 تا 12 آیکون های مربوط به لایک و اشتراک گذاری وجود نداره و تو نمایش مشکل داره
اسکرین شات های مربوط به هر کدوم رو هم قرار دادم
![1PNG](https://github.com/shirvanie/flutter_story/assets/68433686/7bcd3bdb-ddcc-45a8-9e57-3fd7a0fcbcbe)
![2](https://github.com/shirvanie/flutter_story/assets/68433686/493cdbbe-cf2c-49fd-9f51-2e1db81468cf)
![3](https://github.com/shirvanie/flutter_story/assets/68433686/45ef621f-f555-44a7-a9e0-01976518c1ed)

**Comment by shirvanie** [comment]
برای حل این مشکل از کد زیر استفاده کنید. با تغییر Height و Width کلاس StoryUser میتوانید مدیریت کنید 



```
return Scaffold(
  body: SafeArea(
    child: Story(
      height: 100,
      children: [
        StoryUser(
          height: 56,
          width: 56,
          avatar: Image.asset("assets/user_avatar.jpg"),
          label: const Text("UserName"),
          children: const [
            StoryCard(
              footer: StoryCardFooter(
                messageBox: StoryCardMessageBox(),
                likeButton: StoryCardLikeButton(),
                forwardButton: StoryCardForwardButton(),
              ),
              child: Center(
                child: Text(
                  "This is the story card widget",
                  style: TextStyle(color: Colors.white),
                ),
              ),
            )
          ],
        )
      ],
    ),
  ),
);
```



و برای حل مشکل آیکن ها خط زیر در ترمینال اجرا کنید

```
flutter pub add cupertino_icons
```
